// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW38HNAunkYVvP6eVndkwYQ8FweUSxx8o',
    appId: '1:407700982276:web:ff31cd381b26deba68c351',
    messagingSenderId: '407700982276',
    projectId: 'cyber-arcade-76787',
    authDomain: 'cyber-arcade-76787.firebaseapp.com',
    storageBucket: 'cyber-arcade-76787.firebasestorage.app',
    measurementId: 'G-4380ZB1M8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKRveevkELlhzsgiHcq7SEtsYWfN3y_yg',
    appId: '1:407700982276:android:965e6dd28623eb2568c351',
    messagingSenderId: '407700982276',
    projectId: 'cyber-arcade-76787',
    storageBucket: 'cyber-arcade-76787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHPdEYDhCkQqHhJT52px5haPTYFmeefO0',
    appId: '1:407700982276:ios:35e52a77b1c04a8268c351',
    messagingSenderId: '407700982276',
    projectId: 'cyber-arcade-76787',
    storageBucket: 'cyber-arcade-76787.firebasestorage.app',
    androidClientId: '407700982276-jbns6qlfo3kqmgu2s59q8rp3bcbdgsdq.apps.googleusercontent.com',
    iosClientId: '407700982276-nqkkl7fos0tbmqusptmcu9mmlg9631qe.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHPdEYDhCkQqHhJT52px5haPTYFmeefO0',
    appId: '1:407700982276:ios:35e52a77b1c04a8268c351',
    messagingSenderId: '407700982276',
    projectId: 'cyber-arcade-76787',
    storageBucket: 'cyber-arcade-76787.firebasestorage.app',
    androidClientId: '407700982276-jbns6qlfo3kqmgu2s59q8rp3bcbdgsdq.apps.googleusercontent.com',
    iosClientId: '407700982276-nqkkl7fos0tbmqusptmcu9mmlg9631qe.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW38HNAunkYVvP6eVndkwYQ8FweUSxx8o',
    appId: '1:407700982276:web:3c4195aff1de4ecd68c351',
    messagingSenderId: '407700982276',
    projectId: 'cyber-arcade-76787',
    authDomain: 'cyber-arcade-76787.firebaseapp.com',
    storageBucket: 'cyber-arcade-76787.firebasestorage.app',
    measurementId: 'G-Z9VV5EB1SP',
  );
}
